import type{ContextSnapshot,LatentEntityState}from'../types';

const common=['skill','form','health','usage','experience','potential','chemistry'];
function pct(v:number|undefined){if(v===undefined)return '—';return `${v>=0?'+':''}${(v*100).toFixed(0)}`}
function label(k:string){return k.replaceAll('_',' ')}
function tone(v:number){return v>.12?'positive':v<-.12?'negative':'neutral'}
function EntityCard({entity}:{entity:LatentEntityState}){const dims=common.filter(k=>k in entity.dimensions);return <article className="belief-card"><div className="belief-head"><div><strong>{entity.display_name}</strong><small>{entity.role??entity.entity_type} · {entity.evidence_count} evidence items · {entity.estimator_version}</small></div><span className="confidence">{(entity.confidence*100).toFixed(0)}% conf.</span></div><div className="dimension-grid">{dims.map(k=>{const sd=Math.sqrt(Math.max(0,entity.dimension_variance?.[k]??0));return <div key={k}><span>{label(k)}</span><b className={tone(entity.dimensions[k])}>{pct(entity.dimensions[k])}</b><small>posterior σ {(sd*100).toFixed(0)}</small></div>})}</div>{entity.recent_evidence.length>0&&<div className="evidence-list">{entity.recent_evidence.slice(0,3).map((e,i)=><div key={`${e.metric}-${i}`}><span>{label(e.metric)}</span><strong>{String(e.raw_value)}{e.unit?` ${e.unit}`:''}</strong><small>{e.source_id}</small></div>)}</div>}</article>}

export function ContextIntelligencePanel({context}:{context:ContextSnapshot}){const teams=context.entity_states.filter(e=>e.entity_type==='team');const people=context.entity_states.filter(e=>e.entity_type!=='team').sort((a,b)=>b.confidence-a.confidence).slice(0,6);return <div className="context-stack"><div className="context-summary"><div><span>Historical strength</span><strong>{pct(context.aggregate_features.historical_strength_diff)}</strong></div><div><span>Recent form</span><strong>{pct(context.aggregate_features.recent_form_diff)}</strong></div><div><span>Health state</span><strong>{pct(context.aggregate_features.health_diff)}</strong></div><div><span>Matchup</span><strong>{pct(context.aggregate_features.matchup_advantage)}</strong></div><div><span>Public context</span><strong>{pct(context.aggregate_features.context_mean_shift)}</strong></div><div><span>Volatility</span><strong>{((context.aggregate_features.context_volatility??0)*100).toFixed(0)}%</strong></div></div><div className="belief-columns"><div><h3>Team belief state</h3><div className="belief-list">{teams.map(e=><EntityCard key={e.entity_id} entity={e}/>)}</div></div><div><h3>Key people / units</h3><div className="belief-list">{people.map(e=><EntityCard key={e.entity_id} entity={e}/>)}</div></div></div>{context.matchup_edges.length>0&&<div className="context-section"><h3>Matchup graph</h3><div className="matchup-list">{context.matchup_edges.map((m,i)=><div className="matchup-row" key={`${m.label}-${i}`}><div><strong>{m.label}</strong><small>{m.rationale}</small></div><span className={tone(m.advantage)}>{pct(m.advantage)}</span><small>{(m.confidence*100).toFixed(0)}% conf.</small></div>)}</div></div>}<div className="context-section"><h3>Human & situational context</h3>{context.signals.length===0?<p className="muted">No point-in-time-valid public context signals are available yet.</p>:<div className="signal-list">{context.signals.slice(0,8).map(s=><div className="signal-row" key={s.signal_id}><div><div className="signal-title"><strong>{s.label}</strong><span className={`sentiment ${s.sentiment}`}>{s.sentiment}</span><span>{s.effect}</span></div><p>{s.summary}</p><small>{s.category} · {s.source_id} · known {new Date(s.known_to_model_time).toLocaleString()}</small></div><div className="signal-meta"><b>{(s.confidence*100).toFixed(0)}%</b><small>confidence</small></div></div>)}</div>}</div><div className="context-foot">Belief state as of {new Date(context.as_of).toLocaleString()} · all evidence filtered by <code>known_to_model_time ≤ prediction cutoff</code>. Public-language signals are evidence, not inferred private mental states.</div></div>}
