import{useQuery}from'@tanstack/react-query';import{getJSON}from'../lib/api';

type Row=Record<string,any>;
const f4=(x?:number|null)=>x==null?'—':x.toFixed(4);
const LEAGUE_NAME:Record<string,string>={nfl:'NFL','college-football':'FBS',nba:'NBA',nhl:'NHL',wnba:'WNBA','mens-college-basketball':'NCAAM','womens-college-basketball':'NCAAW'};

export function SeasonReplay(){const q=useQuery({queryKey:['season-summary'],queryFn:()=>getJSON<{summary:Row[]}>('/research/season-summary')});const rows=q.data?.summary??[];const leagues=[...new Set(rows.map(r=>r.league))];
return <article className="panel wide"><div className="panel-title"><span>Historical season replay · is the season simulator calibrated?</span><small>point-in-time rebuild at 0/25/50/75% of each season; rating hyper-parameters fit on earlier seasons only</small></div>
<p className="muted note">Same world state, two simulators. FAST treats games as independent coin flips at the posterior mean. DYNAMIC samples each team's true strength once per simulated season (correlated futures). A calibrated 90% interval should cover ≈ 90% of final win totals.</p>
<div className="table-wrap"><table className="team-table"><thead><tr><th>League</th><th>Checkpoint</th><th>Mode</th><th>90% win-interval coverage</th><th>Playoff log loss</th><th>(base rate)</th><th>Wins MAE</th><th>(pace baseline)</th><th>Champion log loss</th><th>(uniform)</th></tr></thead><tbody>
{leagues.flatMap(lg=>rows.filter(r=>r.league===lg).sort((a,b)=>a.checkpoint-b.checkpoint||a.mode.localeCompare(b.mode)).map((r,i)=><tr key={lg+i} className={r.mode==='dynamic'?'':'muted'}><td>{i===0?LEAGUE_NAME[lg]??lg:''}</td><td>{Math.round(r.checkpoint*100)}%</td><td>{r.mode.toUpperCase()}</td><td><span className={Math.abs((r.wins_90_coverage??0)-0.9)<0.06?'positive':'negative'}>{r.wins_90_coverage!=null?(r.wins_90_coverage*100).toFixed(0)+'%':'—'}</span></td><td>{f4(r.playoff_log_loss)}</td><td className="muted">{f4(r.playoff_log_loss_base_rate)}</td><td>{r.wins_mae?.toFixed(2)}</td><td className="muted">{r.wins_mae_pace_baseline?.toFixed(2)}</td><td>{f4(r.champion_log_loss)}</td><td className="muted">{f4(r.champion_uniform_log_loss)}</td></tr>))}</tbody></table></div></article>}

export function Bakeoffs(){const q=useQuery({queryKey:['bakeoffs'],queryFn:()=>getJSON<Row[]>('/research/bakeoffs')});
return <article className="panel wide"><div className="panel-title"><span>In-game win-probability bake-off · real play-by-play</span><small>chronological 60/20/20 split · temperature-calibrated on the calibration window · untouched test window</small></div>
{(q.data??[]).map(b=><div key={b.file} className="bakeoff"><h4>{LEAGUE_NAME[b.league]??b.league} · {b.kind==='pbp'?'play-by-play states':'every 3rd snap'} · {b.test?.toLocaleString()} test rows{b.data_fingerprint&&<small className="muted"> · data {b.data_fingerprint.hash}</small>}</h4>
<table className="team-table"><thead><tr><th>Model</th><th>Log loss</th><th>Brier</th><th>ECE</th><th>{b.kind==='pbp'?'In-game only LL':'Same plays as ESPN · LL'}</th></tr></thead><tbody>{Object.entries(b.models as Record<string,Row>).map(([k,m])=><tr key={k}><td>{k.replaceAll('_',' ')}</td><td>{f4(m.log_loss)}</td><td>{f4(m.brier)}</td><td>{f4(m.ece)}</td><td>{f4(m.same_plays_as_espn?.log_loss??m.in_game_only?.log_loss)}</td></tr>)}</tbody></table>
{Object.keys(b.paired_game_bootstrap??{}).length>0&&<table className="team-table"><thead><tr><th>Paired comparison (resampling whole games)</th><th>Δ log loss</th><th>95% CI</th><th>Verdict</th></tr></thead><tbody>{Object.entries(b.paired_game_bootstrap as Record<string,Row>).map(([k,c])=>{const ci=c.ci95??[0,0];const verdict=ci[1]<0?'A significantly better':ci[0]>0?'A significantly worse':'no significant difference';return <tr key={k}><td>{k.replaceAll('_',' ')}</td><td>{(c.mean_log_loss_diff??c.mean)?.toFixed(5)}</td><td>[{ci[0].toFixed(4)}, {ci[1].toFixed(4)}]</td><td className={ci[1]<0?'positive':ci[0]>0?'negative':'muted'}>{verdict}</td></tr>})}</tbody></table>}</div>)}
{q.data?.length===0&&<p className="muted">No bake-off reports yet.</p>}</article>}

export function PlayerImpact(){const q=useQuery({queryKey:['player-impact'],queryFn:()=>getJSON<Row[]>('/research/player-impact')});
return <article className="panel wide"><div className="panel-title"><span>Learned player-availability impact</span><small>residual of actual margin vs point-in-time Kalman expectation, regressed on key-player absences (ex-post participation)</small></div>
<table className="team-table"><thead><tr><th>League</th><th>Absence</th><th>Effect (points / goals)</th><th>±SE</th><th>t</th><th>Games with absence</th><th>Games</th></tr></thead><tbody>{(q.data??[]).flatMap(d=>Object.entries(d.by_position as Record<string,Row>).map(([pos,v],i)=><tr key={d.league+pos}><td>{i===0?LEAGUE_NAME[d.league]??d.league:''}</td><td>{pos==='QB'?'starting QB out':pos==='G'?'starting goalie out':'per top-2 minutes player out'}</td><td className="negative">{v.points.toFixed(2)}</td><td>{v.se.toFixed(2)}</td><td>{v.t}</td><td>{v.games_with_absence}</td><td>{d.n_games}</td></tr>))}</tbody></table><p className="muted note">Serving: live ESPN injury reports → P(plays) (status mapping is an uncalibrated, labelled prior) → team strength delta = effect × (1 − P(plays)) → every affected future game and the season run are recomputed.</p></article>}

export function Consensus(){const q=useQuery({queryKey:['consensus'],queryFn:()=>getJSON<Row[]>('/research/consensus')});const rows=(q.data??[]).filter(r=>r.status==='scored');
return <article className="panel wide"><div className="panel-title"><span>External consensus · betting market vs SportsWorld (pregame)</span><small>identical out-of-sample games · market de-vigged · benchmark only, never a feature</small></div>
{rows.length===0?<p className="muted">Consensus benchmark not available yet.</p>:<table className="team-table"><thead><tr><th>League</th><th>Games</th><th>SportsWorld LL</th><th>Market LL</th><th>Δ (SW − market) 95% CI</th><th>Corr.</th><th>|Δp| mean</th><th>A6 blend vs market (same later-half games)</th></tr></thead><tbody>{rows.map(r=>{const m=r.metrics;const pd=m.paired_log_loss_difference??{};const ci=pd.ci95??pd.ci_95??[null,null];return <tr key={r.league}><td>{LEAGUE_NAME[r.league]??r.league}</td><td>{r.matched_games}</td><td>{f4(m.sportsworld?.log_loss)}</td><td>{f4(m.market?.log_loss)}</td><td>{f4(pd.observed_mean??pd.mean)} [{f4(ci[0])}, {f4(ci[1])}]</td><td>{m.disagreement?.correlation?.toFixed(3)}</td><td>{m.disagreement?.mean_absolute_probability_difference?.toFixed(3)}</td><td>{f4(m.A6_research_only_blend_ablation?.out_of_sample_log_loss)} vs {f4(m.A6_research_only_blend_ablation?.market_out_of_sample_log_loss)}<br/><small className="muted">w(SW) {m.A6_research_only_blend_ablation?.weights?.sportsworld_logit?.toFixed(2)} · w(mkt) {m.A6_research_only_blend_ablation?.weights?.market_logit?.toFixed(2)}</small></td></tr>})}</tbody></table>}
<p className="muted note">Markets aggregate injury news, lineups and money; SportsWorld is an independent, auditable world model. The gap measures what that extra information is worth — and where the two disagree is where the interesting research lives.</p></article>}

export function Rolling(){const q=useQuery({queryKey:['rolling'],queryFn:()=>getJSON<Row[]>('/research/rolling')});const rows=q.data??[];
return <article className="panel wide"><div className="panel-title"><span>Rolling-origin evaluation · train ≤ O−2, calibrate O−1, test O</span><small>walk-forward across seasons; mean ± sd over origins</small></div>
{rows.length===0?<p className="muted">Rolling-origin runs not available yet.</p>:<table className="team-table"><thead><tr><th>League</th><th>Origins</th><th>Model LL (mean ± sd)</th><th>Kalman-only LL</th><th>Model − Kalman by origin</th></tr></thead><tbody>{rows.map(r=><tr key={r.league}><td>{LEAGUE_NAME[r.league]??r.league}</td><td>{r.origins?.map((o:Row)=>o.origin_season).join(', ')}</td><td>{f4(r.model_log_loss_mean)} ± {f4(r.model_log_loss_sd)}</td><td>{f4(r.kalman_only_log_loss_mean)} ± {f4(r.kalman_only_log_loss_sd)}</td><td>{(r.model_minus_kalman_by_origin??[]).map((x:number)=>(x>0?'+':'')+x.toFixed(4)).join(' · ')}</td></tr>)}</tbody></table>}</article>}
