// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import AddWinProbReducer from "../add_win_prob_reducer";
import AddWorldUpdateReducer from "../add_world_update_reducer";
import DropGamesReducer from "../drop_games_reducer";
import PublishCompetitionReducer from "../publish_competition_reducer";
import PublishGamesReducer from "../publish_games_reducer";
import PublishTeamsReducer from "../publish_teams_reducer";

export type AddWinProbParams = __Infer<typeof AddWinProbReducer>;
export type AddWorldUpdateParams = __Infer<typeof AddWorldUpdateReducer>;
export type DropGamesParams = __Infer<typeof DropGamesReducer>;
export type PublishCompetitionParams = __Infer<typeof PublishCompetitionReducer>;
export type PublishGamesParams = __Infer<typeof PublishGamesReducer>;
export type PublishTeamsParams = __Infer<typeof PublishTeamsReducer>;

