// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  league: __t.string().primaryKey(),
  globalStateVersion: __t.u64().name("global_state_version"),
  runId: __t.string().name("run_id"),
  asOf: __t.string().name("as_of"),
  status: __t.string(),
  draws: __t.u32(),
  playedGames: __t.u32().name("played_games"),
  remainingGames: __t.u32().name("remaining_games"),
  liveGames: __t.u32().name("live_games"),
  updatedAt: __t.timestamp().name("updated_at"),
});
