// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  eventId: __t.string().primaryKey().name("event_id"),
  league: __t.string(),
  startTime: __t.string().name("start_time"),
  state: __t.string(),
  homeId: __t.string().name("home_id"),
  awayId: __t.string().name("away_id"),
  homeScore: __t.u32().name("home_score"),
  awayScore: __t.u32().name("away_score"),
  period: __t.u32(),
  clockSeconds: __t.f64().name("clock_seconds"),
  pHome: __t.f64().name("p_home"),
  leverageHome: __t.f64().name("leverage_home"),
  leverageAway: __t.f64().name("leverage_away"),
  stateVersion: __t.u64().name("state_version"),
});
