// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  league: __t.string(),
  globalStateVersion: __t.u64(),
  runId: __t.string(),
  asOf: __t.string(),
  status: __t.string(),
  draws: __t.u32(),
  playedGames: __t.u32(),
  remainingGames: __t.u32(),
  liveGames: __t.u32(),
};
