// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  key: __t.string().primaryKey(),
  league: __t.string(),
  teamId: __t.string().name("team_id"),
  name: __t.string(),
  conference: __t.string(),
  rating: __t.f64(),
  ratingSd: __t.f64().name("rating_sd"),
  expectedWins: __t.f64().name("expected_wins"),
  qualify: __t.f64(),
  conferenceTitle: __t.f64().name("conference_title"),
  title: __t.f64(),
  stateVersion: __t.u64().name("state_version"),
});
