// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Competition = __t.object("Competition", {
  league: __t.string(),
  globalStateVersion: __t.u64(),
  runId: __t.string(),
  asOf: __t.string(),
  status: __t.string(),
  draws: __t.u32(),
  playedGames: __t.u32(),
  remainingGames: __t.u32(),
  liveGames: __t.u32(),
  updatedAt: __t.timestamp(),
});
export type Competition = __Infer<typeof Competition>;

export const Config = __t.object("Config", {
  key: __t.string(),
  owner: __t.identity(),
});
export type Config = __Infer<typeof Config>;

export const Game = __t.object("Game", {
  eventId: __t.string(),
  league: __t.string(),
  startTime: __t.string(),
  state: __t.string(),
  homeId: __t.string(),
  awayId: __t.string(),
  homeScore: __t.u32(),
  awayScore: __t.u32(),
  period: __t.u32(),
  clockSeconds: __t.f64(),
  pHome: __t.f64(),
  leverageHome: __t.f64(),
  leverageAway: __t.f64(),
  stateVersion: __t.u64(),
});
export type Game = __Infer<typeof Game>;

export const GameRow = __t.object("GameRow", {
  eventId: __t.string(),
  startTime: __t.string(),
  state: __t.string(),
  homeId: __t.string(),
  awayId: __t.string(),
  homeScore: __t.u32(),
  awayScore: __t.u32(),
  period: __t.u32(),
  clockSeconds: __t.f64(),
  pHome: __t.f64(),
  leverageHome: __t.f64(),
  leverageAway: __t.f64(),
});
export type GameRow = __Infer<typeof GameRow>;

export const TeamOdds = __t.object("TeamOdds", {
  key: __t.string(),
  league: __t.string(),
  teamId: __t.string(),
  name: __t.string(),
  conference: __t.string(),
  rating: __t.f64(),
  ratingSd: __t.f64(),
  expectedWins: __t.f64(),
  qualify: __t.f64(),
  conferenceTitle: __t.f64(),
  title: __t.f64(),
  stateVersion: __t.u64(),
});
export type TeamOdds = __Infer<typeof TeamOdds>;

export const TeamRow = __t.object("TeamRow", {
  teamId: __t.string(),
  name: __t.string(),
  conference: __t.string(),
  rating: __t.f64(),
  ratingSd: __t.f64(),
  expectedWins: __t.f64(),
  qualify: __t.f64(),
  conferenceTitle: __t.f64(),
  title: __t.f64(),
});
export type TeamRow = __Infer<typeof TeamRow>;

export const Viewer = __t.object("Viewer", {
  connectionId: __t.connectionId(),
  connectedAt: __t.timestamp(),
});
export type Viewer = __Infer<typeof Viewer>;

export const WinProb = __t.object("WinProb", {
  id: __t.u64(),
  eventId: __t.string(),
  at: __t.string(),
  pHome: __t.f64(),
});
export type WinProb = __Infer<typeof WinProb>;

export const WinProbRow = __t.object("WinProbRow", {
  eventId: __t.string(),
  at: __t.string(),
  pHome: __t.f64(),
});
export type WinProbRow = __Infer<typeof WinProbRow>;

export const WorldUpdate = __t.object("WorldUpdate", {
  id: __t.u64(),
  league: __t.string(),
  at: __t.string(),
  reason: __t.string(),
  teams: __t.string(),
  stateVersion: __t.u64(),
});
export type WorldUpdate = __Infer<typeof WorldUpdate>;

